-- MySQL Script generated by MySQL Workbench
-- Wed Jul 21 10:18:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`court`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`court` ;

CREATE TABLE IF NOT EXISTS `mydb`.`court` (
  `numero` INT NOT NULL,
  `couvert` TINYINT NOT NULL,
  `surface` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`match` ;

CREATE TABLE IF NOT EXISTS `mydb`.`match` (
  `idmatch` INT NOT NULL,
  `date` DATE NULL,
  `type` VARCHAR(45) NULL,
  `nomJoueur1` VARCHAR(16) NULL,
  `nomJoueur2` VARCHAR(16) NULL,
  `court_numero` INT NOT NULL,
  PRIMARY KEY (`idmatch`, `court_numero`),
  INDEX `fk_match_court_idx` (`court_numero` ASC),
  CONSTRAINT `fk_match_court`
    FOREIGN KEY (`court_numero`)
    REFERENCES `mydb`.`court` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`joueur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`joueur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`joueur` (
  `id` INT NOT NULL,
  `nom` VARCHAR(16) NOT NULL,
  `prenom` VARCHAR(16) NULL,
  `age` INT NOT NULL,
  `classement` VARCHAR(10) NULL,
  `match_idmatch` INT NOT NULL,
  PRIMARY KEY (`id`, `match_idmatch`),
  INDEX `fk_joueur_match1_idx` (`match_idmatch` ASC),
  CONSTRAINT `fk_joueur_match1`
    FOREIGN KEY (`match_idmatch`)
    REFERENCES `mydb`.`match` (`idmatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reservation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `idreservation` INT NOT NULL,
  `nomJoueur` VARCHAR(16) NULL,
  `jour` VARCHAR(16) NULL,
  `heure` VARCHAR(16) NULL,
  `joueur_id` INT NOT NULL,
  `court_numero` INT NOT NULL,
  PRIMARY KEY (`idreservation`, `joueur_id`),
  INDEX `fk_reservation_joueur1_idx` (`joueur_id` ASC),
  INDEX `fk_reservation_court1_idx` (`court_numero` ASC),
  CONSTRAINT `fk_reservation_joueur1`
    FOREIGN KEY (`joueur_id`)
    REFERENCES `mydb`.`joueur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_court1`
    FOREIGN KEY (`court_numero`)
    REFERENCES `mydb`.`court` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
